// grade_decision / compute_divergence — wrap advice-ledger-kit's gradeDecision
// and computeDivergence: grade the grader itself, closing the loop on
// whether a recommendation engine's advice was taken and whether it turned
// out right.
//
// Two tools, not one, same reasoning as append_audit_entry / verify_audit_chain:
// grading one decision against a before/after observation log and measuring
// divergence between two judges over a whole population are genuinely
// different operations with different inputs, even though both live in the
// same kit.
//
// `computeDivergence`'s real config accepts a `groupBy: (pair) => string |
// null` function for custom bucketing. MCP arguments are JSON and cannot
// carry a function value, so `compute_divergence` accepts it as a
// `groupBySource` JS source string and, when supplied, runs the whole
// computeDivergence call inside a worker_threads Worker with a bounded
// timeout (see lib/runFunctionJob.ts) -- same treatment, and same trust
// model, as check_payout_invariance's rankFnSource / check_mutation_invariance's
// fnSource. Omitting groupBySource falls back to the library's own default,
// which buckets by each pair's own `group` field -- that covers the common
// case without needing any code execution (or a worker) at all, so that path
// still runs computeDivergence directly on the main thread.

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  gradeDecision,
  describeGrade,
  computeDivergence,
  describeDivergence,
  type DivergenceResult,
} from "advice-ledger-kit";
import { runFunctionJob } from "../lib/runFunctionJob.js";
import { errorMessage, errorResult, jsonResult } from "../lib/result.js";

// ---------------------------------------------------------------------------
// grade_decision
// ---------------------------------------------------------------------------

const recommendationSchema = z.object({
  id: z
    .string()
    .describe("Stable identifier for this recommendation. `decision.recommendationId` must equal this exactly, or grading is refused."),
  subjectId: z.string().describe("What the advice is about: a project, a machine, a queue, an account."),
  checkKey: z
    .string()
    .describe(
      "The thing later observations report on -- this is what makes a recommendation gradeable at all. " +
        "An empty/whitespace-only checkKey is always refused ('no_gradeable_check_key'), since no observation " +
        "could ever be matched back to it.",
    ),
  proposedAt: z
    .string()
    .describe(
      "ISO-8601 timestamp the recommendation was proposed. Use one consistent format for every proposedAt/" +
        "decidedAt/observedAt in a given ledger -- dates are compared as strings, and mixing 'YYYY-MM-DD' with " +
        "a full timestamp compares wrongly.",
    ),
  basis: z
    .enum(["observed", "model-proposed"])
    .optional()
    .describe(
      "Where the recommendation came from. 'observed' = derived from something the system actually counted. " +
        "'model-proposed' = generated by a model reasoning over the corpus (still gradeable unless " +
        "config.requireObservedBasis is set). Defaults to 'observed' when omitted.",
    ),
});

const decisionSchema = z.object({
  recommendationId: z.string().describe("Must equal recommendation.id, or grading is refused with 'decision_recommendation_mismatch'."),
  status: z.enum(["adopted", "dismissed"]).describe("Whether the human took the advice."),
  decidedAt: z
    .string()
    .min(1, "decidedAt must not be empty -- the kit treats an empty string as invalid, not as an unknown timestamp.")
    .describe(
      "ISO-8601 timestamp of the human's call. Observations strictly before this form the baseline window; " +
        "observations strictly after (and exposed) form the result window; observations timestamped exactly " +
        "at this instant are counted (`atBoundaryObservations`) but grade neither window. Must be non-empty.",
    ),
});

const observationSchema = z.object({
  subjectId: z.string().describe("Matched against recommendation.subjectId -- only observations on the same subject are considered."),
  checkKey: z.string().describe("Matched against recommendation.checkKey -- only observations of the same check are considered."),
  state: z.enum(["good", "bad"]).describe("Whether this dated reading found the thing fine ('good') or not ('bad')."),
  observedAt: z
    .string()
    .min(1, "observedAt must not be empty -- the kit treats an empty string as invalid, not as an unknown timestamp.")
    .describe("ISO-8601 timestamp of this reading. Compared as a string against decidedAt -- use one consistent format. Must be non-empty."),
  exposed: z
    .boolean()
    .optional()
    .describe(
      "LOAD-BEARING: whether the recommendation could actually have applied on this occasion. Only " +
        "observations with exposed === true, strictly after decidedAt, can create or reverse the headline " +
        "'result' verdict. Omitted and false are both treated as not-exposed on purpose -- an unanswered " +
        "exposure question is not a confirmed exposure. Ignored for observations before decidedAt (the advice " +
        "was not in force yet, so there was nothing for it to be exposed to).",
    ),
});

const gradeConfigSchema = z
  .object({
    minBaselineObservations: z.number().int().min(1).optional().describe("Minimum pre-decision observations. Default 3."),
    minResultObservations: z.number().int().min(1).optional().describe("Minimum post-decision observations of any exposure. Default 3."),
    minExposedResultObservations: z
      .number()
      .int()
      .min(1)
      .optional()
      .describe("Minimum post-decision observations where the advice could apply. Default 3."),
    minBaselineBadObservations: z
      .number()
      .int()
      .min(0)
      .optional()
      .describe(
        "Minimum 'bad' observations in the baseline. Default 1. A baseline with no bad readings gives the " +
          "advice nothing to have improved -- this is the floor a naive 'no gap since adoption' grader misses.",
      ),
    proposeThreshold: z
      .number()
      .int()
      .min(1)
      .optional()
      .describe("How many bad observations it took to justify emitting this recommendation in the first place. Default 2."),
    refuteThreshold: z
      .number()
      .int()
      .min(1)
      .optional()
      .describe(
        "How many bad exposed post-decision observations it takes to overturn the decision. Defaults to " +
          "proposeThreshold (symmetric). Setting this BELOW proposeThreshold throws -- refuting more cheaply " +
          "than you proposed is a thumb on the scale, not conservatism.",
      ),
    requireObservedBasis: z
      .boolean()
      .optional()
      .describe("When true, a 'model-proposed' recommendation is refused outright ('basis_not_gradeable'). Default false."),
  })
  .optional()
  .describe(
    "Floors and thresholds, every field optional with a library default (see advice-ledger-kit's " +
      "DEFAULT_GRADE_CONFIG). Omit entirely to use the library's defaults.",
  );

/** Registers `grade_decision` on `server`. */
export function registerAdviceLedgerGradeTool(server: McpServer): void {
  server.registerTool(
    "grade_decision",
    {
      title: "Grade a decision against what happened after it",
      description:
        "Grades one recommendation-and-decision pair against a before/after observation log. Compares a pre-" +
        "decision BASELINE window to a post-decision, exposure-aligned RESULT window on the same subjectId + " +
        "checkKey, and returns 'holding' (the exposed post-decision window stayed under `refuteThreshold` bad " +
        "observations), 'not-holding' (the exposed post-decision window hit `refuteThreshold` bad " +
        "observations), or " +
        "'refused' (the evidence didn't clear a floor -- see refusalCodes for exactly which one, never a " +
        "vague 'unproven'). OPEN DESIGN QUESTION, read before trusting a 'holding' verdict: this is a " +
        "THRESHOLD COUNT, not a rate comparison -- 'holding' can come back even while the bad rate rose (1 " +
        "bad of 10 before, 1 bad of 3 since is still 'holding' at the default bar). Always show `badRateDelta` " +
        "and the raw `baseline`/`result` counts next to the verdict, don't quote 'holding' on its own. The " +
        "verdict grades the DECISION, not just whether advice was taken: a DISMISSED recommendation whose " +
        "problem later surfaced also grades 'not-holding', because the evidence sided with the advice either " +
        "way. Two things this tool refuses to let slide: (1) 'nothing has gone wrong since' only counts as a " +
        "result if the baseline shows the problem existed before -- otherwise it's " +
        "'baseline_lacks_negative_signal'; (2) only observations where the advice could actually have applied " +
        "(exposed === true) can create or reverse the headline verdict -- everything else is reported " +
        "separately as `secondary` (whose own `wouldBeVerdict` can itself be 'refused'), labelled " +
        "non-headline, and can never become the headline. Use this to close the loop on any recommender/" +
        "advisor system that logs recommendations, human accept/reject calls, and later outcomes, instead of " +
        "letting advice quality go unmeasured forever. For grading a whole population of engine-vs-human calls " +
        "at once (rather than one decision against its own before/after window), use compute_divergence instead.",
      inputSchema: {
        decision: decisionSchema.describe("The human's call on the recommendation."),
        recommendation: recommendationSchema.describe("The advice being graded."),
        observations: z
          .array(observationSchema)
          .describe(
            "Every observation available. This tool does the filtering by subjectId + checkKey itself, so " +
              "passing the whole ledger (observations for other subjects/checks too) is fine.",
          ),
        config: gradeConfigSchema,
      },
    },
    ({ decision, recommendation, observations, config }) => {
      try {
        const grade = gradeDecision(decision, recommendation, observations, config ?? {});
        return jsonResult(describeGrade(grade), grade);
      } catch (err) {
        return errorResult(errorMessage(err));
      }
    },
  );
}

// ---------------------------------------------------------------------------
// compute_divergence
// ---------------------------------------------------------------------------

const judgmentPairSchema = z.object({
  engineJudgment: z
    .string()
    .describe(
      "What the system said. Compared to humanJudgment by exact equality -- use one canonical spelling per " +
        "judgment. An empty string counts as 'didn't speak' for comparability purposes, same as omitting it.",
    ),
  humanJudgment: z
    .string()
    .describe("What the human said. Same equality and 'didn't speak' treatment as engineJudgment."),
  laterOutcome: z
    .string()
    .optional()
    .describe(
      "What actually turned out to be the case, when that is known yet. Compared by exact equality against " +
        "engineJudgment/humanJudgment to settle who was right on a divergent pair. Omit if not yet known.",
    ),
  group: z
    .string()
    .optional()
    .describe("Optional bucket, used by the default groupBy to produce the per-group breakdown. Ignored if config.groupBySource is supplied."),
  id: z.string().optional().describe("Optional identifier, carried through into `examples` on a divergence report."),
});

const divergenceConfigSchema = z
  .object({
    minComparablePairs: z.number().int().min(1).optional().describe("Minimum pairs where both judges spoke. Default 10."),
    minDivergentCount: z.number().int().min(1).optional().describe("Minimum disagreements. Default 3."),
    minDivergentRate: z
      .number()
      .min(0)
      .max(1)
      .optional()
      .describe(
        "Minimum disagreement share of comparable pairs, 0 to 1. Default 0.05. Both this AND " +
          "minDivergentCount must clear before divergence is 'reportable' -- either floor alone lets pure " +
          "noise through (a 100% rate on 3 of 3 occasions, or a real rate buried in a huge sample).",
      ),
    minResolvedDivergent: z
      .number()
      .int()
      .min(1)
      .optional()
      .describe("Minimum disagreements that also have a later outcome, before naming who was right. Default 3."),
    exampleLimit: z.number().int().min(0).optional().describe("How many divergent pairs to carry through as examples. Default 10."),
    groupBySource: z
      .string()
      .optional()
      .describe(
        "JS source for a pure function `(pair) => string | null` -- the real kit's `groupBy` config. MCP " +
          "arguments are JSON and cannot carry a function value, so when supplied this runs the whole " +
          "computeDivergence call in a worker thread with a bounded timeout (default 10s, see README) instead " +
          "of on the main thread (same trust model as check_payout_invariance's rankFnSource -- only pass code " +
          "you wrote or trust). Return null from it to leave a pair out of the per-group breakdown entirely. " +
          "Omit to use the library's own default, which buckets by each pair's own `group` field -- that " +
          "covers the common case with no code execution (or worker) at all.",
      ),
  })
  .optional()
  .describe(
    "Floors, thresholds, and optional custom grouping, every field optional with a library default (see " +
      "advice-ledger-kit's DEFAULT_DIVERGENCE_CONFIG). Omit entirely to use the library's defaults.",
  );

/** Registers `compute_divergence` on `server`. */
export function registerAdviceLedgerDivergenceTool(server: McpServer): void {
  server.registerTool(
    "compute_divergence",
    {
      title: "Measure where two judges disagree, and who was right",
      description:
        "Computes how often two independent judges (e.g. an automated engine and a human override) rated the " +
        "same object differently, and -- where a later outcome exists to settle it -- reports engineRight and " +
        "humanRight as two SEPARATE counts, never combined into one blended accuracy number (a system can be " +
        "right most of the time overall and still wrong every single time a human bothers to overrule it, and " +
        "that second fact is the one worth acting on). Divergence needs BOTH a count floor " +
        "(minDivergentCount) and a rate floor (minDivergentRate) before it's 'reportable' -- either alone lets " +
        "noise through. Calibration (who was right) carries its own separate floor (minResolvedDivergent) and " +
        "its own status, so a population can legitimately have reportable divergence and refused calibration " +
        "at the same time: plenty of disagreements, not enough of them settled by a later outcome yet. Supply " +
        "`group` on each pair (or a custom config.groupBySource) to also get a sorted per-group breakdown " +
        "alongside the overall report. Use this whenever a system has both an automated judgment and a human " +
        "override/correction recorded for the same objects, to find out whether overruling the system is " +
        "actually earning its keep. For grading one recommendation's own before/after outcome window instead " +
        "of a whole population of engine-vs-human calls, use grade_decision.",
      inputSchema: {
        pairs: z
          .array(judgmentPairSchema)
          .describe("Every occasion both judges could have spoken on. Pairs missing one judgment are still counted, just not comparable."),
        config: divergenceConfigSchema,
      },
    },
    async ({ pairs, config }) => {
      try {
        const { groupBySource, ...floors } = config ?? {};
        const result = groupBySource
          ? await runFunctionJob<DivergenceResult>({
              kind: "divergence-group-by",
              pairs,
              floors,
              groupBySource,
            })
          : computeDivergence(pairs, floors);
        const groupsNote =
          result.groups.length > 0
            ? ` Per-group breakdown also computed for ${result.groups.length} group(s).`
            : "";
        return jsonResult(`${describeDivergence(result.overall)}${groupsNote}`, result);
      } catch (err) {
        return errorResult(errorMessage(err));
      }
    },
  );
}
